### ISSUE TITLE
Email user feature

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/github-profile-summary-api#26]
Summary: Using Mailgun node package, allow the ability for a visitor to email the GitHub user through a POST request

- [ ] Use mailgun node package https://www.npmjs.com/package/mailgun-js

- [ ]  Create new controller emailController.js in src/controllers/emailController.js

- [ ] new endpoint should be of the form `/api/v1/email/user` and have a body like:
```
{
  senderEmail: String,
  subject: String,
  message: String
}
```

- [ ] Add a new validator in src/controllers/validators/email/index.js that will check for the above body. No empty strings allowed.

**Comment by mkkhedawat** [comment]
I will check this out. Assign it to me.

**Comment by TheWillG** [comment]
Sounds good, just sent you a collaborator invite!

**Comment by mkkhedawat** [comment]
Raised https://github.com/TheWillG/github-profile-summary-api/pull/30
But couldn't test happy flow as my mailgun account is not getting activated.

**Comment by theblindprophet** [comment]
We will test tonight. Both @TheWillG and I have valid Mailgun accounts.
