### ISSUE TITLE
(Still Available) Report API endpoint and validation

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/github-profile-summary-api#32]
Summary: Create the endpoint and get the user data from GitHub. Do not worry about the POST body that is attached to this request. Just validate the POST body and send back a 200. This concerns a separate issue.

- [ ] New endpoint with path /github/userData/:userName/report
- [ ] Validator in src/controllers/validators/report that accepts `userName` as path param and the following body:
```
{
  languageChart: String, // dataUri format
  commitChart: String, // dataUri format,
}
```
- [ ] Send's back 200 if successful and validation passes

**Comment by AllDayAlone** [comment]
I can take this one @TheWillG

**Comment by TheWillG** [comment]
@AllDayAlone great, it's all yours!

**Comment by TheWillG** [comment]
@AllDayAlone any updates on this issue?

**Comment by lourdesr** [comment]
Hey @TheWillG - is this still available ? If yes, can I work on this ?

**Comment by lourdesr** [comment]
Thanks, I just pulled in the latest code. All tests are passing in `npm run test`. 
However, when I run `npm run start` - it throws an error and crashes. 

Looking into it, I find that the error is from mailgun.js It throws the error at "apiKey value must be defined"

![screen shot 2018-10-04 at 5 32 08 pm](https://user-images.githubusercontent.com/3199404/46501301-78ab2180-c7fb-11e8-87c2-ecc3064d3325.png)

**Comment by TheWillG** [comment]
Can you chat on Gitter? Join the chat in DylloProfileSummary/Lobby

**Comment by lourdesr** [comment]
Ah, looks like I need to add mailgun domain and key in the env.
