### ISSUE TITLE
Beginner friendly - Calculate user's top language

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/github-profile-summary-api#35]
Summary: We want to be able to show what language the user has the most experience with. For this we will need a new githubService function.

- [ ] Add a new function to src/services/githubService.js called `calculatedTopLanguage(userLanguagePercents)` and call it from within `getUserData`
- [ ] Take `userLanguagePercents` function input, and calculate the top language and return it as a String
- [ ] Add `topLanguage` as key to return object `userData`, so userData will now look like 
```
// userData return object from function getUserData
{
  ...,
  ...,
  topLanguage: "JavaScript"
}
```

**Comment by alissonmdo** [comment]
I'll do it!

**Comment by mehtankush** [comment]
can this be taken up by multiple people?

**Comment by TheWillG** [comment]
@alissonmdo it's all yours!

**Comment by theblindprophet** [comment]
@mehtankush It would difficult to do so. We are steadily thinking of new issues though, so check back. If it's not finish in a reasonable amount of time you can have it.

**Comment by alissonmdo** [comment]
@mehtankush you can take it, I'm having problems with my nodejs hahaha.

**Comment by TheWillG** [comment]
@mehtankush if you are still interested you can take ownership of this issue

**Comment by lukebrobbs** [comment]
If this is available, I’d love to have a go? It would be ok the morning as it is evening in the uk 🙂

**Comment by TheWillG** [comment]
@lukebrobbs I do not believe anybody is working on this at the moment, so yes, it's all yours

**Comment by mehtankush** [comment]
Raised #40 

Please advice.
