### ISSUE TITLE
(Still Available) Beginner Friendly - Whitelist CORS

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/github-profile-summary-api#36]
Summary: Since we only want our web-app and localhost:3000 to hit the API, we want to whitelist those two domains and block everything else. This can be done by implementing a simple CORS policy.
- [ ] In lib/config/index.js, add a whitelist array and include https://githubprofilesummary.com/ and localhost:3000 as the two strings in the array.
- [ ] Add npm package cors to project (https://www.npmjs.com/package/cors)
- [ ] In app.js, import whitelist from config and follow this example to use cors middleware (https://www.npmjs.com/package/cors#configuring-cors-w-dynamic-origin)
- [ ] Instead of adding cors to each individual request, please just add it as middleware using `app.use(cors(corsOptions))` so it will apply to all requests

**Comment by mehtankush** [comment]
@TheWillG I am interested. Please assign this to me?

**Comment by TheWillG** [comment]
@mehtankush sounds great, it's all yours

**Comment by mehtankush** [comment]
Raised #37 

Please advice.

**Comment by lourdesr** [comment]
Hey @TheWillG - if this is still available, I want to try :)

**Comment by TheWillG** [comment]
@lourdesr Please take it, I don't think anybody is working on it anymore

**Comment by lourdesr** [comment]
Thanks! 😄
